### ISSUE TITLE
Medals and translations

### ISSUE THREAD

**Issue by WillCalderwood** [WillCalderwood/WordBuzz#19]
How would you feel about getting rid of the number suffix on the medals, so we just have 1, 2 and 3 rather than 1st, 2nd and 3rd? I'm just thinking about translations. The other option is that I could draw the text onto the image, but that never looks quite as sharp.

**Comment by Ironside74** [comment]
Here are the replacement images:
![1st-medal](https://cloud.githubusercontent.com/assets/1868160/5620106/61166c30-9520-11e4-88b8-4d2dfa99063f.png)
![2nd-medal](https://cloud.githubusercontent.com/assets/1868160/5620105/61158aa4-9520-11e4-9b43-d9243f1cdb30.png)
![3rd-medal](https://cloud.githubusercontent.com/assets/1868160/5620104/611381be-9520-11e4-8063-e3a3d19a4223.png)
