### ISSUE TITLE
World Ranking Buttons

### ISSUE THREAD

**Issue by WillCalderwood** [WillCalderwood/WordBuzz#20]
I have a few issues with the world ranking button.

1. Where to put it. See attached.

2. What it should be called? It's not really a world ranking button, but a social ranking button for Google play that can also display world rankings. Maybe it should be a Google Play button of some sort?

3. What it should look like. I'm thinking it should be a round button in the corner of the screen to match the back button rather than text. That also solves issue 1.

![screenshot_2015-01-05-16-15-55](https://cloud.githubusercontent.com/assets/6973062/5615780/63e68122-94f6-11e4-9566-190012349773.png)

**Comment by Ironside74** [comment]
Here's the visual...
![ranking-visual](https://cloud.githubusercontent.com/assets/1868160/5620115/81b1fcb6-9520-11e4-99f8-28141ea76ed2.png)
and the button graphic...
![world-ranking](https://cloud.githubusercontent.com/assets/1868160/5620119/8f785462-9520-11e4-9841-2369722b4025.png)
