### ISSUE TITLE
Invite Friends button

### ISSUE THREAD

**Issue by WillCalderwood** [WillCalderwood/WordBuzz#22]
Please can you knock something up when you get time. I'm not too sure where to place it either. I guess somewhere on the landing screen. Maybe replace the Facebook Connect button once they're connected?

We could move the credits button elsewhere as that doesn't really need to be there. I just need it somewhere for legal reasons. Maybe under the settings dialog?

**Comment by Ironside74** [comment]
This could go bottom centre, which would mean the rest of the buttons can stay as they are.
![invite-friend-btn](https://cloud.githubusercontent.com/assets/1868160/5919795/11785204-a62f-11e4-9bde-c7a9c29020ad.png)

**Comment by WillCalderwood** [comment]
Thanks for that. It'll only work bottom centre in portrait. I wouldn't fit in landscape.

What about getting rid of the text and just having the icon, then using a round button and putting it in line with the other buttons on the right hand side. Right centre? Or move the credits button onto the settings dialog maybe? And have the invite friends button top right.

As I'm sure we'll be adding a few more buttons to the landing screen, for example, a shop button. We could just add circular buttons down the sides of the screen as needed? Or will that look a bit crap?

**Comment by Ironside74** [comment]
I would move the credits button on to the settings dialogue and place this button top right. We could then add a shop button next to this when needed. We need to keep the buttons at the top and bottom if we can. I'll update the graphic shortly.

**Comment by Ironside74** [comment]
![invite-friends-btn](https://cloud.githubusercontent.com/assets/1868160/5924121/d5cc8d8e-a650-11e4-8053-2b85d9a29197.png)

**Comment by WillCalderwood** [comment]
Where do you think I should stick the credits button on the settings dialogue? I'm struggling to make it look good.

![image](https://cloud.githubusercontent.com/assets/6973062/5941930/2aa087aa-a70c-11e4-92ec-8cc38d7b31f1.png)

**Comment by Ironside74** [comment]
I'll work up a visual later

**Comment by Ironside74** [comment]
How's this?...
![settings](https://cloud.githubusercontent.com/assets/1868160/5946645/4818fbe6-a72f-11e4-8ea8-a2b66bc6256a.png)

**Comment by WillCalderwood** [comment]
Looks good. Certainly a lot better than what I was trying to do.

**Comment by Ironside74** [comment]
Cool! Here's the credits button:
![credits-btn](https://cloud.githubusercontent.com/assets/1868160/5946801/6024bf30-a730-11e4-87c4-7b615bb51c75.png)

**Comment by WillCalderwood** [comment]
Don't worry about the text on the buttons. I can add that at runtime. Makes
translations much less hassle for you.
