### ISSUE TITLE
Error icon

### ISSUE THREAD

**Issue by WillCalderwood** [WillCalderwood/WordBuzz#23]
I'm currently using your close button (the cross) as an error icon in dialogs when displaying errors. Please could you knock up something more appropriate when you have time. It's a little misleading.

Thanks

![image](https://cloud.githubusercontent.com/assets/6973062/5667147/5b6c03d2-975d-11e4-8d5c-1d065f36c0b4.png)

**Comment by Ironside74** [comment]
![error](https://cloud.githubusercontent.com/assets/1868160/5919569/ef20ac62-a62c-11e4-97eb-f159596863f9.png)
